// Generated by CI at build time from the git commit SHA — do not commit the
// real value. The placeholder below makes it obvious a build skipped the
// bake step (see .github/workflows/ota.yml) instead of silently showing a
// stale/wrong SHA.
enum BuildInfo {
    static let gitSHA = "NO_SHA_BAKED_IN"
}
