// Generated by CI at build time from the PICNIC_MIRROR_TOKEN secret — do not
// commit the real value. The placeholder below is intentionally invalid so a
// build that skipped the bake step (see .github/workflows/ota.yml) fails
// loudly with 401s instead of silently mirroring with no auth.
enum MirrorToken {
    static let value = "NO_TOKEN_BAKED_IN"
}
