import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { AlbumStore } from '../lib/album.mjs';
import { buildTrimArgs, probeDurationSec } from '../lib/video-trim.mjs';
import { downloadKept } from '../album-fetch.mjs';

const dir = mkdtempSync(join(tmpdir(), 'picnic-album-trim-test-'));
const tokenPath = join(dir, 'token');
const TOKEN = 'trim-test-token';
writeFileSync(tokenPath, TOKEN);
process.env.PICNIC_TOKEN_PATH = tokenPath;
process.env.PICNIC_QUEUE_PATH = join(dir, 'queue.jsonl');
process.env.PICNIC_THUMBS_DIR = join(dir, 'thumbs');
process.env.PICNIC_RECONCILE_DIR = join(dir, 'reconcile');
process.env.PICNIC_ALBUMS_DIR = join(dir, 'albums');

const { createApp } = await import('../queue-server.mjs');
const server = createApp();
await new Promise((r) => server.listen(0, '127.0.0.1', r));
const base = `http://127.0.0.1:${server.address().port}`;
test.after(() => {
  server.close();
  rmSync(dir, { recursive: true, force: true });
});

const A = (key) => [key, [`https://lh3.example/${key}`, 100, 50], 1700000000000, 'dedupe', 0, 1];
const auth = { Authorization: `Bearer ${TOKEN}` };
const post = (path, body, headers = auth) =>
  fetch(`${base}${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...headers }, body: JSON.stringify(body) });
const fakeResponse = (body, type = 'video/mp4', status = 200) =>
  new Response(body, { status, headers: { 'content-type': type } });

/** Real 4s 160x120 10fps clip with audio, generated by ffmpeg itself. */
const clipPath = join(dir, 'clip.mp4');
execFileSync('ffmpeg', [
  '-y', '-hide_banner', '-loglevel', 'error',
  '-f', 'lavfi', '-i', 'testsrc=d=4:s=160x120:r=10', '-f', 'lavfi', '-i', 'sine=d=4',
  '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-c:a', 'aac', '-shortest', clipPath,
]);
const clipBytes = readFileSync(clipPath);

function freshStore(name = 'alb') {
  return new AlbumStore(mkdtempSync(join(dir, 'store-')), name);
}

test('buildTrimArgs: input-side -ss before -i, -t is a length, re-encodes, rejects bad ranges', () => {
  const args = buildTrimArgs({ input: '/in.mov', output: '/out.mp4', startSec: 1.5, endSec: 4 });
  assert.ok(args.indexOf('-ss') < args.indexOf('-i'), '-ss must precede -i for fast frame-accurate seek');
  assert.equal(args[args.indexOf('-ss') + 1], '1.5');
  assert.equal(args[args.indexOf('-i') + 1], '/in.mov');
  assert.equal(args[args.indexOf('-t') + 1], '2.5', '-t is endSec - startSec');
  assert.ok(!args.includes('-c') && args.includes('libx264'), 'a keyframe-only copy would start early');
  assert.equal(args.at(-1), '/out.mp4');
  assert.throws(() => buildTrimArgs({ input: 'a', output: 'b', startSec: 2, endSec: 2 }), /invalid trim range/);
  assert.throws(() => buildTrimArgs({ input: 'a', output: 'b', startSec: -1, endSec: 2 }), /invalid trim range/);
  assert.throws(() => buildTrimArgs({ input: 'a', output: 'b', startSec: 0, endSec: NaN }), /invalid trim range/);
});

test('setTrim: validates, last write wins, listItems exposes trim (null when none)', () => {
  const s = freshStore();
  s.ingestItems([A('p1'), A('v1'), A('v2')]);
  s.mergeKinds({ p1: 'photo', v1: 'video', v2: 'video' });
  assert.deepEqual(s.setTrim('v1', 1, 3), { startSec: 1, endSec: 3 });
  assert.deepEqual(s.setTrim('v1', 0.5, 2), { startSec: 0.5, endSec: 2 });
  assert.deepEqual(s.listItems().map((i) => i.trim), [null, { startSec: 0.5, endSec: 2 }, null]);
  assert.throws(() => s.setTrim('p1', 0, 1), /not a video/);
  assert.throws(() => s.setTrim('nope', 0, 1), /unknown mediaKey/);
  assert.throws(() => s.setTrim('../v1', 0, 1), /invalid mediaKey/);
  assert.throws(() => s.setTrim('v1', -1, 1), /startSec must be >= 0/);
  assert.throws(() => s.setTrim('v1', 2, 2), /at least/);
  assert.throws(() => s.setTrim('v1', 3, 1), /at least/);
  assert.throws(() => s.setTrim('v1', '0', 1), /finite number/);
  assert.throws(() => s.setTrim('v1', 0, Infinity), /finite number/);
  assert.throws(() => s.setTrim('v1', 0, 10, 4), /past the video duration/);
  assert.deepEqual(s.setTrim('v1', 0, 4.3, 4), { startSec: 0, endSec: 4.3 }, 'within the slack is accepted');
});

test('POST /album/:id/trim/:key: auth, validation vs the real cached duration, listing round trip', async () => {
  const path = '/album/trimalb/trim/v1';
  assert.equal((await post('/album/trimalb/items', { items: [A('p1'), A('v1'), A('v2')] })).status, 200);
  const store = new AlbumStore(process.env.PICNIC_ALBUMS_DIR, 'trimalb');
  store.mergeKinds({ p1: 'photo', v1: 'video', v2: 'video' });
  store.writeVideo('v1', clipBytes); // real 4s mp4: the route ffprobes it

  assert.equal((await post(path, { startSec: 1, endSec: 2 }, {})).status, 401);
  const ok = await post(path, { startSec: 1, endSec: 3 });
  assert.equal(ok.status, 200);
  assert.deepEqual(await ok.json(), { ok: true, trim: { startSec: 1, endSec: 3 } });
  assert.equal((await post(path, { startSec: 1, endSec: 99 })).status, 400, 'end past the 4s clip');
  assert.equal((await post(path, { startSec: 3, endSec: 2 })).status, 400);
  assert.equal((await post(path, { startSec: 'a', endSec: 2 })).status, 400);
  assert.equal((await post('/album/trimalb/trim/p1', { startSec: 0, endSec: 1 })).status, 400, 'photo');
  assert.equal((await post('/album/trimalb/trim/zzz', { startSec: 0, endSec: 1 })).status, 400, 'unknown key');
  assert.equal((await post('/album/trimalb/trim/v2', { startSec: 0, endSec: 500 })).status, 200,
    'an uncached video has no duration to check against');

  const list = await (await fetch(`${base}/album/trimalb`, { headers: auth })).json();
  assert.deepEqual(list.items.map((i) => i.trim), [null, { startSec: 1, endSec: 3 }, { startSec: 0, endSec: 500 }]);
});

test('downloadKept: trimmed kept video fetches =dv and cuts via trimFn; untrimmed video and photos stay =d', async () => {
  const s = freshStore();
  s.ingestItems([A('v1'), A('v2'), A('p1')]);
  s.mergeKinds({ v1: 'video', v2: 'video', p1: 'photo' });
  for (const k of ['v1', 'v2', 'p1']) s.setDecision(k, 'keep');
  s.setTrim('v1', 1, 2.5);
  const urls = [];
  const fetchFn = async (u) => {
    urls.push(u);
    return u.includes('p1') ? fakeResponse('photo', 'image/jpeg') : fakeResponse('original-video');
  };
  const calls = [];
  const trimFn = async ({ input, output, startSec, endSec }) => {
    calls.push({ startSec, endSec, inputBytes: readFileSync(input, 'utf8') });
    writeFileSync(output, 'trimmed-bytes');
  };
  const r = await downloadKept(s, { fetchFn, trimFn, paceMs: 0, log: () => {} });
  assert.deepEqual([r.ok, r.failed], [3, 0]);
  assert.deepEqual(urls, ['https://lh3.example/v1=dv', 'https://lh3.example/v2=d', 'https://lh3.example/p1=d']);
  assert.deepEqual(calls, [{ startSec: 1, endSec: 2.5, inputBytes: 'original-video' }]);
  assert.equal(readFileSync(s.fullPath('v1'), 'utf8'), 'trimmed-bytes');
  assert.ok(s.fullPath('v1').endsWith('v1.mp4'));
  assert.equal(readFileSync(s.fullPath('v2'), 'utf8'), 'original-video', 'untrimmed video downloads as-is');
});

test('downloadKept: an ffmpeg failure counts as failed and leaves no full/ file', async () => {
  const s = freshStore();
  s.ingestItems([A('v1')]);
  s.mergeKinds({ v1: 'video' });
  s.setDecision('v1', 'keep');
  s.setTrim('v1', 0, 1);
  const logs = [];
  const r = await downloadKept(s, {
    fetchFn: async () => fakeResponse('x'.repeat(10)),
    trimFn: async () => { throw new Error('ffmpeg exploded'); },
    paceMs: 0, log: (m) => logs.push(m),
  });
  assert.deepEqual([r.ok, r.failed], [0, 1]);
  assert.ok(logs.some((m) => m.includes('full FAILED v1: ffmpeg exploded')));
  assert.equal(s.fullPath('v1'), null);
});

test('REAL ffmpeg: downloadKept cuts a 4s clip to the 1.0-3.0 range (output duration about 2s)', async () => {
  const s = freshStore();
  s.ingestItems([A('v1')]);
  s.mergeKinds({ v1: 'video' });
  s.setDecision('v1', 'keep');
  s.setTrim('v1', 1, 3);
  const before = await probeDurationSec(clipPath);
  assert.ok(Math.abs(before - 4) < 0.3, `source should be ~4s, got ${before}`);
  const r = await downloadKept(s, { fetchFn: async () => fakeResponse(clipBytes), paceMs: 0, log: () => {} });
  assert.deepEqual([r.ok, r.failed], [1, 0]);
  const out = s.fullPath('v1');
  assert.ok(out && existsSync(out));
  const after = await probeDurationSec(out);
  assert.ok(Math.abs(after - 2) < 0.3, `trimmed clip should be ~2s, got ${after}`);
});
